changelog:
  categories:
  - title: Features
    labels:
    - enhancement
    - feature
  - title: Bug Fixes
    labels:
    - bug
    - fix
  - title: Documentation
    labels:
    - documentation
    - docs
  - title: CI/CD
    labels:
    - ci
    - github_actions
  - title: Dependencies
    labels:
    - dependencies
  - title: Other Changes
    labels:
    - "*"
