name: "Rust CI"

on:
  push:
    paths:
    - "crates/**"
    - "Cargo.toml"
    - "rust-toolchain.toml"
  pull_request:
    paths:
    - "crates/**"
    - "Cargo.toml"
    - "rust-toolchain.toml"

permissions:
  contents: read

jobs:
  check:
    name: "Build, Test, Lint"
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

    - name: "Install Rust"
      uses: dtolnay/rust-toolchain@631a55b12751854ce901bb631d5902ceb48146f7 # stable
      with:
        components: clippy, rustfmt

    - name: "Cache"
      uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: rust-${{ hashFiles('**/Cargo.toml') }}
        restore-keys: rust-

    - name: "Check"
      run: cargo check --workspace

    - name: "Test"
      run: cargo test --workspace

    - name: "Clippy"
      run: cargo clippy --workspace -- -D warnings

    - name: "Format"
      run: cargo fmt --all -- --check
